export const cssVariablesLight = {
  "--tg-theme-hint-color": "#999999",
  "--tg-theme-secondary-bg-color": "#efeff3",
  "--tg-theme-text-color": "#000000",
  "--memo-text-color-disabled": "#808080",
  "--tg-theme-button-color": "#2481cc",
  "--memo-button-color-alpha-20": "#2481cc33",
  "--memo-button-color-alpha-40": "#2481cc66",
  "--memo-button-color-darkened": "#1c66a1",
  "--tg-theme-bg-color": "#ffffff",
  "--tg-theme-button-text-color": "#ffffff",
  "--tg-theme-link-color": "#2481cc",
  "--tg-viewport-height": "100vh",
  "--tg-viewport-stable-height": "100vh",
};

export const cssVariablesDark = {
  "--tg-theme-hint-color": "#b1c3d5",
  "--tg-theme-secondary-bg-color": "#131415",
  "--tg-theme-text-color": "#ffffff",
  "--memo-text-color-disabled": "#92a3b3",
  "--tg-theme-button-color": "#2ea6ff",
  "--memo-button-color-alpha-20": "#2ea6ff33",
  "--memo-button-color-alpha-40": "#2ea6ff66",
  "--memo-button-color-darkened": "#0090fa",
  "--tg-theme-bg-color": "#18222d",
  "--tg-theme-button-text-color": "#ffffff",
  "--tg-theme-link-color": "#62bcf9",
  "--tg-viewport-height": "100vh",
  "--tg-viewport-stable-height": "100vh",
};
