import type { SpeakLanguageEnum } from "./speak";

export const highQualityVoices: Partial<Record<SpeakLanguageEnum, string[]>> = {
  ["en-US"]: [
    "Microsoft EmmaMultilingual Online (Natural) - English (United States)",
    "Microsoft AvaMultilingual Online (Natural) - English (United States)",
    "Microsoft Jenny Online (Natural) - English (United States)",
    "Microsoft Aria Online (Natural) - English (United States)",
    "Microsoft Michelle Online (Natural) - English (United States)",
    "Microsoft Ana Online (Natural) - English (United States)",
    "Microsoft AndrewMultilingual Online (Natural) - English (United States)",
    "Microsoft BrianMultilingual Online (Natural) - English (United States)",
    "Microsoft Guy Online (Natural) - English (United States)",
    "Microsoft Eric Online (Natural) - English (United States)",
    "Microsoft Steffan Online (Natural) - English (United States)",
    "Microsoft Christopher Online (Natural) - English (United States)",
    "Microsoft Roger Online (Natural) - English (United States)",
    "Ava",
    "Zoe",
    "Allison",
    "Nicky",
    "Samantha",
    "Joelle",
    "Evan",
    "Nathan",
    "Tom",
    "Alex",
    "Aaron",
    "Google US English",
    "Microsoft Zira - English (United States)",
    "Microsoft David - English (United States)",
    "Microsoft Mark - English (United States)",
    "Google US English 5 (Natural)",
    "Google US English 1 (Natural)",
    "Google US English 2 (Natural)",
    "Google US English 7 (Natural)",
    "Android Speech Recognition and Synthesis from Google en-us-x-sfg-network",
    "Chrome OS US English 8",
    "Google US English 4 (Natural)",
    "Google US English 3 (Natural)",
    "Google US English 6 (Natural)",
  ],
  "en-GB": [
    "Microsoft Sonia Online (Natural) - English (United Kingdom)",
    "Microsoft Libby Online (Natural) - English (United Kingdom)",
    "Microsoft Maisie Online (Natural) - English (United Kingdom)",
    "Microsoft Ryan Online (Natural) - English (United Kingdom)",
    "Microsoft Thomas Online (Natural) - English (United Kingdom)",
    "Kate",
    "Stephanie",
    "Serena",
    "Martha",
    "Jamie",
    "Oliver",
    "Daniel",
    "Arthur",
    "Google UK English Female",
    "Google UK English Male",
    "Microsoft Hazel - English (Great Britain)",
    "Microsoft Susan - English (Great Britain)",
    "Microsoft George - English (Great Britain)",
    "Google UK English 2 (Natural)",
    "Google UK English 4 (Natural)",
    "Google UK English 6 (Natural)",
    "Chrome OS UK English 7",
    "Google UK English 1 (Natural)",
    "Google UK English 3 (Natural)",
    "Google UK English 5 (Natural)",
  ],
  "de-DE": [
    "Microsoft SeraphinaMultilingual Online (Natural) - German (Germany)",
    "Microsoft Amala Online (Natural) - German (Germany)",
    "Microsoft Katja Online (Natural) - German (Germany)",
    "Microsoft FlorianMultilingual Online (Natural) - German (Germany)",
    "Microsoft Conrad Online (Natural) - German (Germany)",
    "Microsoft Killian Online (Natural) - German (Germany)",
    "Petra",
    "Anna",
    "Helena",
    "Markus",
    "Viktor",
    "Yannick",
    "Martin",
    "Weibliche Google-Stimme (Deutschland)",
    "Microsoft Hedda - German (Germany)",
    "Microsoft Katja - German (Germany)",
    "Microsoft Stefan - German (Germany)",
    "Google Deutsch 2 (Natural)",
    "Google Deutsch 1 (Natural)",
    "Google Deutsch 3 (Natural)",
    "Google Deutsch 4 (Natural)",
  ],
  "es-ES": [
    "Microsoft Elvira Online (Natural) - Spanish (Spain)",
    "Microsoft Alvaro Online (Natural) - Spanish (Spain)",
    "Marisol",
    "Mónica",
    "Jorge",
    "Google español",
    "Microsoft Helena - Spanish (Spain)",
    "Microsoft Laura - Spanish (Spain)",
    "Microsoft Pablo - Spanish (Spain)",
    "Google español 4 (Natural)",
    "Google español 1 (Natural)",
    "Google español 2 (Natural)",
    "Google español 3 (Natural)",
    "Google español 5 (Natural)",
  ],
  "ru-RU": [
    "Microsoft Svetlana Online (Natural) - Russian (Russia)",
    "Microsoft Ekaterina Online - Russian (Russia)",
    "Microsoft Dmitry Online (Natural) - Russian (Russia)",
    "Katya",
    "Milena",
    "Yuri",
    "Google русский",
    "Microsoft Irina - Russian (Russian)",
    "Microsoft Pavel - Russian (Russian)",
    "Android Speech Recognition and Synthesis from Google ru-ru-x-dfc-network",
    "Android Speech Recognition and Synthesis from Google ru-ru-x-ruc-network",
    "Android Speech Recognition and Synthesis from Google ru-ru-x-rue-network",
    "Android Speech Recognition and Synthesis from Google ru-ru-x-rud-network",
    "Android Speech Recognition and Synthesis from Google ru-ru-x-ruf-network",
  ],
  "ja-JP": [
    "Microsoft Nanami Online (Natural) - Japanese (Japan)",
    "Microsoft Keita Online (Natural) - Japanese (Japan)",
    "O-Ren",
    "Kyoko",
    "Otoya",
    "Hattori",
    "Google 日本語",
    "Microsoft Ayumi - Japanese (Japan)",
    "Microsoft Haruka - Japanese (Japan)",
    "Microsoft Ichiro - Japanese (Japan)",
    "Google 日本語 1 (Natural)",
    "Chrome OS 日本語 2",
    "Google 日本語 2 (Natural)",
    "Google 日本語 3 (Natural)",
  ],
  "ar-001": ["Mariam", "Laila", "Tarik", "Majed"],
  "th-TH": [
    "Microsoft Premwadee Online (Natural) - Thai (Thailand)",
    "Microsoft Niwat Online (Natural) - Thai (Thailand)",
    "Narisa",
    "Kanya",
    "Microsoft Pattara - Thai (Thailand)",
    "Google ไทย (Natural)",
  ],
  "fr-FR": [
    "Microsoft VivienneMultilingual Online (Natural) - French (France)",
    "Microsoft Denise Online (Natural) - French (France)",
    "Microsoft Eloise Online (Natural) - French (France)",
    "Microsoft RemyMultilingual Online (Natural) - French (France)",
    "Microsoft Henri Online (Natural) - French (France)",
    "Audrey",
    "Aurélie",
    "Marie",
    "Thomas",
    "Google français",
    "Microsoft Julie - French (France)",
    "Microsoft Hortence - French (France)",
    "Microsoft Paul - French (France)",
    "Google français 4 (Natural)",
    "Google français 2 (Natural)",
    "Google français 1 (Natural)",
    "Google français 5 (Natural)",
    "Google français 3 (Natural)",
  ],
  "pt-BR": [
    "Microsoft Francisca Online (Natural) - Portuguese (Brazil)",
    "Microsoft ThalitaMultilingual Online (Natural) - Portuguese (Brazil)",
    "Microsoft Antonio Online (Natural) - Portuguese (Brazil)",
    "Fernanda",
    "Luciana",
    "Felipe",
    "Google português do Brasil",
    "Microsoft Maria - Portuguese (Brazil)",
    "Microsoft Daniel - Portuguese (Brazil)",
    "Google português do Brasil 1 (Natural)",
    "Google português do Brasil 3 (Natural)",
    "Google português do Brasil 2 (Natural)",
  ],
};

export const arrayIntersection = (left: string[], right: string[]) => {
  const set = new Set(left);
  return right.filter((item) => set.has(item));
};
