import { SpeakLanguageEnum } from "./speak";

export const highQualityVoices: Partial<Record<SpeakLanguageEnum, string[]>> = {
  [SpeakLanguageEnum.USEnglish]: [
    "Microsoft EmmaMultilingual Online (Natural) - English (United States)",
    "Microsoft AvaMultilingual Online (Natural) - English (United States)",
    "Microsoft Jenny Online (Natural) - English (United States)",
    "Microsoft Aria Online (Natural) - English (United States)",
    "Microsoft Michelle Online (Natural) - English (United States)",
    "Microsoft Ana Online (Natural) - English (United States)",
    "Microsoft AndrewMultilingual Online (Natural) - English (United States)",
    "Microsoft BrianMultilingual Online (Natural) - English (United States)",
    "Microsoft Guy Online (Natural) - English (United States)",
    "Microsoft Eric Online (Natural) - English (United States)",
    "Microsoft Steffan Online (Natural) - English (United States)",
    "Microsoft Christopher Online (Natural) - English (United States)",
    "Microsoft Roger Online (Natural) - English (United States)",
    "Ava",
    "Zoe",
    "Allison",
    "Nicky",
    "Samantha",
    "Joelle",
    "Evan",
    "Nathan",
    "Tom",
    "Alex",
    "Aaron",
    "Google US English",
    "Microsoft Zira - English (United States)",
    "Microsoft David - English (United States)",
    "Microsoft Mark - English (United States)",
    "Google US English 5 (Natural)",
    "Google US English 1 (Natural)",
    "Google US English 2 (Natural)",
    "Google US English 7 (Natural)",
    "Android Speech Recognition and Synthesis from Google en-us-x-sfg-network",
    "Chrome OS US English 8",
    "Google US English 4 (Natural)",
    "Google US English 3 (Natural)",
    "Google US English 6 (Natural)",
  ],
  [SpeakLanguageEnum.UKEnglish]: [
    "Microsoft Sonia Online (Natural) - English (United Kingdom)",
    "Microsoft Libby Online (Natural) - English (United Kingdom)",
    "Microsoft Maisie Online (Natural) - English (United Kingdom)",
    "Microsoft Ryan Online (Natural) - English (United Kingdom)",
    "Microsoft Thomas Online (Natural) - English (United Kingdom)",
    "Kate",
    "Stephanie",
    "Serena",
    "Martha",
    "Jamie",
    "Oliver",
    "Daniel",
    "Arthur",
    "Google UK English Female",
    "Google UK English Male",
    "Microsoft Hazel - English (Great Britain)",
    "Microsoft Susan - English (Great Britain)",
    "Microsoft George - English (Great Britain)",
    "Google UK English 2 (Natural)",
    "Google UK English 4 (Natural)",
    "Google UK English 6 (Natural)",
    "Chrome OS UK English 7",
    "Google UK English 1 (Natural)",
    "Google UK English 3 (Natural)",
    "Google UK English 5 (Natural)",
  ],
};

export const arrayIntersection = (left: string[], right: string[]) => {
  const set = new Set(left);
  return right.filter((item) => set.has(item));
};
